[package]
name = "pomimi"
version = "0.1.0"
edition = "2021"

[package.metadata.bundle]
name = "Pomimi"
identifier = "com.pomimi.pomimi"
icon = ["assets/images/icon.icns"]
category = "Productivity"
short_description = "A beautiful Pomodoro timer"
long_description = "Pomimi is a minimalist Pomodoro timer to help you focus and track your productivity."

[dependencies]
iced = { version = "0.14", default-features = false, features = ["tiny-skia", "tokio", "advanced", "image", "x11", "wayland"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"
chrono = "0.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
